#!/bin/bash

REAL_PATH=$(readlink -m "$BASH_SOURCE")     # echo $REAL_PATH
COMMAND_FILE_NAME=${BASH_SOURCE##*/}        # echo $COMMAND_FILE_NAME
BASH_FILE_NAME=${REAL_PATH##*/}             # echo $BASH_FILE_NAME
FOLDER_PATH=${REAL_PATH%/*}                 # echo $FOLDER_PATH

export VAGRANT_DEV_HOME='/vagrant/vendor/hgraca/vagrant-dev'

PROJECT_OS_NAME=$1
PROJECT_OS_UPGRATE=$2
VM_HOSTNAME=$3
PROJECT_OS_DEPENDENCIES=$4


${VAGRANT_DEV_HOME}/provisioning/${PROJECT_OS_NAME}.sh ${PROJECT_OS_UPGRATE} ${VM_HOSTNAME} "${PROJECT_OS_DEPENDENCIES}"
